### ISSUE TITLE
method_name is null?

### ISSUE THREAD

**Issue by csquan** [eteu-technologies/near-api-go#11]
bugs?
height:65906486
methodName in functioncall of action is null,but mannet db this record is not null .

**Comment by mikroskeem** [comment]
Please give transaction ID so I can easily look it up on the NEAR explorer.

**Comment by csquan** [comment]
tx_hash：AFYNx2sJ64Vwqx5LzgFbmhJ5hJbM8xFLvn93KwAW9YaL

**Comment by mikroskeem** [comment]
Fixed in 23d99e845b91815675da4dd10d9c0e1b01c8a801, thanks.
