### ISSUE TITLE
AddKey and DeleteKey Action unsmarshal failed

### ISSUE THREAD

**Issue by rqzrqh** [eteu-technologies/near-api-go#15]
`{
                        "AddKey": {
                            "access_key": {
                                "nonce": 0,
                                "permission": "FullAccess"
                            },
                            "public_key": "ed25519:Gm4dtdpxNhAyZRDNnjFxiU3P7SMhAnPvpK7YVehFdJgh"
                        }
                    }`

The prefix of the public_key field is  'ed25519:', the action unmarshal function pass it to base58 decoder, however it  can't be recognized.

**Comment by mikroskeem** [comment]
Can you give transaction hash & network?

**Comment by rqzrqh** [comment]
> 
ChunkHash
HLMacUFENvU9M2zkBwcjQrwo6RCMKiBBU5H5GQE4mmhh

**Comment by mikroskeem** [comment]
Fixed as of a6741131fa7eb13b7abf52ac68a6b4d349460416, thank you.
