### ISSUE TITLE
action.AccessKeyPermission unmarshal failed

### ISSUE THREAD

**Issue by rqzrqh** [eteu-technologies/near-api-go#17]
1.What did you try to do (with code snippet to reproduce)

> chunkRsp, err := sw.rpc.ChunkDetails(ctx, chunkHash)

2.What did you expect to see?

>  sync success

3.What did you see instead?

> cannot unmarshal string into Go struct field SignedTransactionView.transactions.actions of type action.AccessKeyPermission 

4.Relevant NEAR network & transaction/block/receipt hash to look up

>  chunk hash 6P3ftNBttmek2Z8nJamXqzmLWkN8yMc4hMHNRDDAfubB

**Comment by mikroskeem** [comment]
Should be fixed as of c042eac16f2136a9b6b464ecb63817e9e2463a25, thank you.
