### ISSUE TITLE
How to distinguish error types

### ISSUE THREAD

**Issue by vic-dayou** [eteu-technologies/near-api-go#20]
The error response of near rpc, [error.cause.name](https://docs.near.org/docs/api/rpc/block-chunk#what-could-go-wrong) can distinguish the error type, but near-api-go does not marsh this information to the error struct, because the error struct does not have a cause field, why not add the cause field to the error struct, like
```go
type Cause struct {
	Info interface{} `json:"info"`
	Name string      `json:"name"`
}

type Error struct {
	Cause   Cause           `json:"cause"`
	Code    int             `json:"code"`
	Message string          `json:"message"`
	Data    json.RawMessage `json:"data"`
}
```

**Comment by mikroskeem** [comment]
#7

**Comment by mikroskeem** [comment]
I think this is solved now.
