### ISSUE TITLE
we don't have this method right? "EXPERIMENTAL_protocol_config"

### ISSUE THREAD

**Issue by elvis-hp** [eteu-technologies/near-api-go#22]

**Comment by elvis-hp** [comment]
please merge for me:
https://github.com/eteu-technologies/near-api-go/pull/23
thanks!

**Comment by mikroskeem** [comment]
Now we do thanks to your efforts. 🎉

**Comment by elvis-hp** [comment]
Hi, just update for the issue, please review and approve for me:
https://github.com/eteu-technologies/near-api-go/pull/24
