### ISSUE TITLE
Unmarshal error:invalid base58 digit (':')

### ISSUE THREAD

**Issue by csquan** [eteu-technologies/near-api-go#9]
when get Block: 65700123
Unmarshal error :invalid base58 digit (':') occured,what happend?

**Comment by mikroskeem** [comment]
Will investigate

**Comment by mikroskeem** [comment]
Found the issue - `ValidatorStakeView` was using `PublicKey` instead of `Base58PublicKey` type. Fix is in master, 90c65280e84b78eb7f40d12c70abb0d6b62bc0fd.

**Comment by csquan** [comment]
yes,can work now, and another question:
when I query  tx after sync block form mainnet, log show :'Server error' (-32000) "DB Not Found Error: BLOCK: EYxj3A2eNTUkeDpbPLgvZCC1SmC2aTDTGDuXkMWvsuEP \n Cause: Unknown",what happened?is there any things about mainnet node?

**Comment by mikroskeem** [comment]
Block `EYxj3A2eNTUkeDpbPLgvZCC1SmC2aTDTGDuXkMWvsuEP` is quite old, `mainnet` RPC will get rid of data which is older than 5 epochs.

You want to query archival node RPC instead, e.g

```shell
go run ./cmd/block --network archival-mainnet --block 'EYxj3A2eNTUkeDpbPLgvZCC1SmC2aTDTGDuXkMWvsuEP'
```

Disregard the issue reopen & close - fat-fingered the button by accident.
